### PR TITLE
A couple more stack files tweaks + update CI

### PR DESCRIPTION
**Pull request by thomasjm**
Follow up to #1368.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Thanks again!

**Comment by thomasjm** [comment]
No problem! Could I get you to look at #1367 @vaibhavsagar? It should be easy to do, and would unblock IHaskell on Nixpkgs for GHC 9.2.

**Comment by vaibhavsagar** [comment]
Hey, I've been putting it off because I have to bump the version numbers and upload everything correctly, a tedious yet detail-oriented task. I will get to it in the next day or two, please feel free to ping me again if that doesn't happen

**Comment by thomasjm** [comment]
Sounds good, thanks for looking into it!

Not sure I totally understand the difficulty -- `ghc-parser` is a standalone package and it doesn't seem like its version number is synced up with anything else (like `ihaskell` proper or any of the display packages). Isn't the whole task just to bump the version number to `0.2.3.1` (I don't think a major bump is even needed) and upload to Hackage? No pressure of course, just excited to get this working :)

**Comment by vaibhavsagar** [comment]
It's not just `ghc-parser`, `ipython-kernel` and `ihaskell` will also need new uploads. My workflow for this could perhaps use improvement but since I do it so infrequently I don't really see the point in making it faster.

**Pull request merged**
